### ISSUE TITLE
undefined method `model_name' for Enumerator:Class

### ISSUE THREAD

**Issue by Dakuan** [hashrocket/decent_exposure#86]
Im getting this error after upgrading from 1.0.2 to 2.0.2 :(
