### ISSUE TITLE
Regression in 3.0.1 - undefined method `stringify_keys' for "subject":String

### ISSUE THREAD

**Issue by bartoszkopinski** [hashrocket/decent_exposure#168]
Hello,

After upgrading to 3.0.1 my entire test suite starts failing. Here is a sample code + rspec error:

``` ruby
ReportMailer.send_report("subject", report_csv).deliver_now!
```

```
NoMethodError:
  undefined method `stringify_keys' for "subject":String
# /home/rof/cache/bundler/ruby/2.3.0/gems/decent_exposure-3.0.1/lib/decent_exposure/mailer.rb:8:in `process_action'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:596:in `block in process'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:593:in `process'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:584:in `initialize'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `new'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `__getobj__'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:34:in `message'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:77:in `deliver_now!'
```

**Comment by mattpolito** [comment]
@bartoszkopinski Thanks for the update, I'll look into this.

**Comment by vnegrisolo** [comment]
@bartoszkopinski @mattpolito I introduced that bug 🐛 some time ago, my bad. I just created a PR to solve that, I hope that this is ok for you!

**Comment by giedriusr** [comment]
Is this going to be merged any time soon?

**Comment by mattpolito** [comment]
@giedriusr This fix has now been released.

**Comment by giedriusr** [comment]
Awesome, thanks 👍
